name: cli - continuous integration

on:
  push:
    branches-ignore:
    - main
    paths:
    - '.github/workflows/cli*'
    - 'cli/**'

defaults:
  run:
    shell: bash
    working-directory: cli

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        stable: true
    - name: build
      run: go build -v ./...
    - name: test
      run: go test -v ./...