name: cli - continuous integration

on:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/cli-*'
    - 'cli/**'

defaults:
  run:
    shell: bash
    working-directory: cli

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        stable: true
    - name: build
      run: go build -v ./...
    - name: test
      run: go test -v ./...
    - name: version bump
      id: version_bump
      uses: mathieudutour/github-tag-action@v5.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: create binary
      env:
        GOOS: darwin
        GOARCH: amd64
      run: |
        mkdir bin
        go build -ldflags="-X 'github.com/mick-roper/petstore/cli/main.Version=${{ steps.version_bump.outputs.new_tag }}'" -o bin/$GOOS/$GOARCH/petstore main.go
    - name: create release
      uses: actions/@create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version_bump.outputs.new_tag }}
        release_name: Release ${{ steps.version_bump.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
