name: cli - continuous integration

on:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/cli-*'
    - 'cli/**'

defaults:
  run:
    shell: bash
    working-directory: cli

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        stable: true
    - name: get deps
      run: go mod vendor
    - name: build
      run: go build -v ./...
    - name: test
      run: go test -v ./...
  create-release:
    strategy:
      matrix:
        goarch: [amd64]
        goos: [linux, darwin, windows]
    runs-on: ubuntu-latest
    needs:
    - build-and-test
    steps:
    - name: version bump
      id: version_bump
      uses: mathieudutour/github-tag-action@v5.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: create package
      run: |
        mkdir bin
        cd bin
        GOOS=${{ matrix.goos }}
        GOARCH=${{ matrix.goarch }}
        BIN_NAME=petstore-${{ matrix.goos }}-${{ matrix.goarch }}
        go build -ldflags="-X 'github.com/mick-roper/petstore/cli/main.Version=${{ steps.version_bump.outputs.new_tag }}'" -o $BIN_NAME main.go
        zip $BIN_NAME.zip $BIN_NAME
    - name: create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version_bump.outputs.new_tag }}
        release_name: Release ${{ steps.version_bump.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
    - name: upload asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: cli/bin/petstore-${{ matrix.goos }}-${{ matrix.goarch }}.zip
        asset_name: petstore-${{ matrix.goos }}-${{ matrix.goarch }}.zip
        asset_content_type: application/zip
