name: cli - build, test and release

on:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/cli-*'
    - 'cli/**'

defaults:
  run:
    shell: bash
    working-directory: cli

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        stable: true
    - name: build
      run: go build -v ./...
    - name: test
      run: go test -v ./...
  create_release:
    runs-on: ubuntu-latest
    needs:
    - build_and_test
    steps:
    - name: version bump
      id: version_bump
      uses: mathieudutour/github-tag-action@v5.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version_bump.outputs.new_tag }}
        release_name: CLI Release ${{ steps.version_bump.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
    outputs:
      tag: ${{ steps.version_bump.outputs.new_tag }}
      release_upload_url: ${{ steps.create_release.outputs.upload_url }}
  create-cli-binaries:
    runs-on: ubuntu-latest
    needs:
    - create_release
    strategy:
      matrix:
        goarch: [amd64]
        goos: [linux, darwin, windows]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        stable: true
    - name: create binary package
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        go build -ldflags="-X 'github.com/mick-roper/petstore/cli/cmd/version.Version=${{ needs.create_release.outputs.tag }}'" -o petstore main.go
        zip petstore-${{ matrix.goos }}-${{ matrix.goarch }}.zip petstore
    - name: upload asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.release_upload_url }}
        asset_path: cli/petstore-${{ matrix.goos }}-${{ matrix.goarch }}.zip
        asset_name: petstore-${{ matrix.goos }}-${{ matrix.goarch }}.zip
        asset_content_type: application/zip
